#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP
/bin/hostname CADTC4412

/bin/mount -n -t proc none /proc
/bin/mount -n -t sysfs none /sys
/bin/mount -t ramfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
/bin/hotplug
# mounting file system specified in /etc/fstab
mkdir -p /dev/pts
mkdir -p /dev/shm
/bin/mount -n -t devpts none /dev/pts -o mode=0622
/bin/mount -n -t tmpfs tmpfs /dev/shm
/bin/mount -n -t ramfs none /tmp
/bin/mount -n -t ramfs none /var
mkdir -p /var/empty
mkdir -p /var/log
mkdir -p /var/lock
mkdir -p /var/run
mkdir -p /var/tmp

/sbin/hwclock -s
syslogd

/sbin/ifconfig lo 127.0.0.1
/sbin/ifconfig eth0 192.168.0.20
/sbin/getty -L ttySAC0 115200 vt100 
#/etc/mkfs_auto

sleep 1
ln -s /dev/video15 /dev/videoa
depmod -A
insmod PCA9685.ko
mknod /dev/pca9685 c 250 0
sleep 1

## should exec 

